### ISSUE TITLE
Installation via opam fails

### ISSUE THREAD

**Issue by haselwarter** [antoinemine/apron#70] opened 2023-01-31 14:57 UTC
On my laptop running Arch Linux, with MPFR 4.2.0, GMP 6.2.1, and OCaml 4.14.1 or 4.12.1, `opam install apron` fails (on a fresh opam switch) to compile apron. Building `master` from source works. `opam pin add --dev-repo apron` can be used as a workaround to install `master` through opam (thanks to `octachron` on `#ocaml`).

**Comment by antoinemine** [comment] 2023-01-31 16:47
Could you please tell me how it fails? What are the logs?

**Comment by haselwarter** [comment] 2023-02-01 08:43
This is the log recorded by opam https://pastebin.mozilla.org/VfV3PeHt

**Comment by antoinemine** [comment] 2023-02-01 08:48
OK, this is a duplicate of #56. The fix is in master and will be included in the next release.

**Comment by maroneze** [comment] 2023-06-21 16:07
Hi,

I just stumbled upon this issue when trying to install apron on an Alpine Linux 3.18 and on a Fedora 38, both of which use Make 4.4. The fix is very useful.

Do you intend to make a release of apron soon? Or would providing a patch file to opam be useful?

**Comment by antoinemine** [comment] 2023-07-27 07:42
There is a beta release for Apron 0.9.14. It has also been submitted to opam.
So, I close this issue. Feel free to reopen f the release does not solve the problem.

**Closed by antoinemine** 2023-07-27 07:42 UTC
